version: '3'

dotenv: ['.env']

tasks:
  # ============ Build & Test ============
  build:
    desc: Build contracts with Foundry
    cmds:
      - forge build

  test:
    desc: Run all Foundry tests
    cmds:
      - forge test -vvv

  build:all:
    desc: Build contracts + SDK
    cmds:
      - task: build
      - task: sdk:build

  # ============ Local Development ============
  dev:start:
    desc: Start local testnet (Anvil + deploy contracts + build SDK) - Press Ctrl+C to stop
    cmds:
      - ./dev/dev-start.sh

  dev:stop:
    desc: Stop any running Anvil node
    cmds:
      - ./dev/stop-anvil.sh

  # ============ Testnet Deployment ============
  deploy:testnet:
    desc: Deploy to Sepolia testnet
    cmds:
      - forge script script/01_DeployCore.s.sol --rpc-url $BASE_SEPOLIA_RPC_URL --broadcast --verify
      - task: sdk:build

  # ============ SDK ============
  sdk:install:
    desc: Install SDK dependencies
    dir: sdk
    cmds:
      - npm install

  sdk:build:
    desc: Build SDK package (generate types + compile)
    dir: sdk
    cmds:
      - npm run build

  sdk:publish:
    desc: Publish SDK to npm
    dir: sdk
    cmds:
      - npm publish
