version: '3'

dotenv: ['.env']

tasks:
  # ============ Build & Test ============
  build:
    desc: Build contracts with Foundry
    cmds:
      - forge build

  test:
    desc: Run all Foundry tests
    cmds:
      - forge test -vvv

  build:all:
    desc: Build contracts + SDK
    cmds:
      - task: build
      - task: sdk:build

  # ============ Local Development ============
  dev:start:
    desc: Start local testnet (Anvil + deploy contracts + build SDK) - Press Ctrl+C to stop
    cmds:
      - ./dev/dev-start.sh

  dev:stop:
    desc: Stop any running Anvil node
    cmds:
      - ./dev/stop-anvil.sh

  # ============ Deployment ============
  deploy:local:
    desc: Deploy to local Anvil (requires Anvil running)
    cmds:
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 forge script script/01_DeployCore.s.sol --rpc-url http://127.0.0.1:8545 --broadcast
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 forge script script/02_SetupLocal.s.sol --rpc-url http://127.0.0.1:8545 --broadcast
      - task: sdk:build

  deploy:testnet:
    desc: Deploy to Sepolia testnet
    cmds:
      - forge script script/01_DeployCore.s.sol --rpc-url $BASE_SEPOLIA_RPC_URL --broadcast --verify
      - task: sdk:build

  # ============ SDK ============
  sdk:install:
    desc: Install SDK dependencies
    dir: sdk
    cmds:
      - npm install

  sdk:build:
    desc: Build SDK package (generate types + compile)
    dir: sdk
    cmds:
      - npm run build

  sdk:publish:
    desc: Publish SDK to npm
    dir: sdk
    cmds:
      - npm publish

  # ============ Indexer ============
  indexer:dev:
    desc: Start indexer in dev mode
    dir: indexer
    cmds:
      - npm run dev

  indexer:clean:
    desc: Clean indexer state in dev mode
    dir: indexer
    cmds:
      - npm run stop

  indexer:test:
    desc: Smoke test indexer GraphQL API
    cmds:
      - |
        curl -X POST http://localhost:8080/graphql \
          -H "Content-Type: application/json" \
          -d '{"query":"{ markets { items { id engine } } }"}'
