// SPDX-License-Identifier: MIT
pragma solidity 0.8.23;

import "forge-std/Script.sol";
import "../src/PerpFactory.sol";
import "../src/LiquidationEngine.sol";
import "../src/FundingManager.sol";
import "../src/MockUSDC.sol";

/**
 * @title DevDeploy
 * @notice Development deployment script with test fixtures
 * @dev Creates factory, markets, test accounts, and sample positions
 *      Fully automated - no prompts, sensible defaults
 */
contract DevDeploy is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");

        vm.startBroadcast(deployerPrivateKey);

        console.log("\n=== Deploying Perp DEX (Dev Mode) ===\n");

        // 1. Deploy MockUSDC
        console.log("1. Deploying MockUSDC...");
        MockUSDC usdc = new MockUSDC();
        console.log("   MockUSDC deployed at:", address(usdc));

        // 2. Deploy shared LiquidationEngine
        console.log("\n2. Deploying shared LiquidationEngine...");
        LiquidationEngine liquidationEngine = new LiquidationEngine();
        console.log("   LiquidationEngine deployed at:", address(liquidationEngine));

        // 3. Deploy shared FundingManager
        console.log("\n3. Deploying shared FundingManager...");
        FundingManager fundingManager = new FundingManager();
        console.log("   FundingManager deployed at:", address(fundingManager));

        // 4. Deploy PerpFactory
        console.log("\n4. Deploying PerpFactory...");
        PerpFactory factory = new PerpFactory(liquidationEngine, fundingManager);
        console.log("   PerpFactory deployed at:", address(factory));

        // 5. Create 3 test markets
        console.log("\n5. Creating test markets...");

        // Default config: 1M base, 2B quote (price = 2000), 30x leverage
        PerpFactory.MarketConfig memory defaultConfig = PerpFactory.MarketConfig({
            baseReserve: 1_000_000 * 1e18,
            quoteReserve: 2_000_000_000 * 1e18,
            maxLeverage: 30 * 1e18
        });

        address spacexEngine = factory.createMarket(address(usdc), defaultConfig);
        console.log("   SPACEX-PERP engine:", spacexEngine);

        address openaiEngine = factory.createMarket(address(usdc), defaultConfig);
        console.log("   OPENAI-PERP engine:", openaiEngine);

        address ventoEngine = factory.createMarket(address(usdc), defaultConfig);
        console.log("   VENTO-PERP engine:", ventoEngine);

        // 6. Get Anvil default accounts (first 5)
        console.log("\n6. Setting up test accounts...");
        address alice = address(0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266); // Anvil #0
        address bob = address(0x70997970C51812dc3A010C7d01b50e0d17dc79C8);   // Anvil #1
        address carol = address(0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC);  // Anvil #2
        address dave = address(0x90F79bf6EB2c4f870365E785982E1f101E93b906);   // Anvil #3
        address eve = address(0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65);    // Anvil #4

        console.log("   Alice:", alice);
        console.log("   Bob:", bob);
        console.log("   Carol:", carol);
        console.log("   Dave:", dave);
        console.log("   Eve:", eve);

        // 7. Mint test USDC to all accounts (10,000 USDC each)
        console.log("\n7. Minting test USDC (10,000 each)...");
        uint256 mintAmount = 10_000 * 1e6; // 10k USDC (6 decimals)

        usdc.mint(alice, mintAmount);
        usdc.mint(bob, mintAmount);
        usdc.mint(carol, mintAmount);
        usdc.mint(dave, mintAmount);
        usdc.mint(eve, mintAmount);

        console.log("   Minted 10,000 USDC to 5 accounts");

        vm.stopBroadcast();

        // 8. Write addresses to .env.development file
        string memory envContent = string.concat(
            "# Auto-generated by DevDeploy.s.sol\n",
            "VITE_USDC_ADDRESS=", vm.toString(address(usdc)), "\n",
            "VITE_FACTORY_ADDRESS=", vm.toString(address(factory)), "\n",
            "VITE_CHAIN_ID=31337\n",
            "VITE_RPC_URL=http://127.0.0.1:8545\n"
        );

        vm.writeFile("web/.env.development", envContent);
        console.log("\nWrote addresses to web/.env.development");

        // 9. Output deployment info
        console.log("\n=== Deployment Complete ===\n");
        console.log("Contract Addresses:");
        console.log("-------------------");
        console.log("USDC:", address(usdc));
        console.log("Factory:", address(factory));
        console.log("\nMarkets:");
        console.log("--------");
        console.log("SpaceX Engine:", spacexEngine);
        console.log("OpenAI Engine:", openaiEngine);
        console.log("Vento Engine:", ventoEngine);

        console.log("\nTest Accounts:");
        console.log("--------------");
        console.log("Alice (0):", alice);
        console.log("Bob (1):", bob);
        console.log("Carol (2):", carol);
        console.log("Dave (3):", dave);
        console.log("Eve (4):", eve);

        console.log("\nNext steps:");
        console.log("-----------");
        console.log("1. Run: task abi:export");
        console.log("2. Run: task web:dev");
        console.log("3. Open browser to http://localhost:5173");
        console.log("4. Connect with Anvil account #0 (Alice)");
        console.log("\n");
    }
}
